name: wo_form_example
description: "A showcase of the multiple possibilities the package wo_form offers."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  freezed_annotation: ^3.0.0
  intl: ^0.20.0
  json_annotation: ^4.9.0
  wo_form: ^1.2.1
  wo_form_service: ^1.0.0

dependency_overrides:
  google_places_flutter:
    path: ../google_places_flutter
  wo_form:
    path: ../wo_form
  wo_form_service:
    path: ../wo_form_service

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
