name: wo_form_example
description: "A showcase of the multiple possibilities the package wo_form offers."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  cloud_functions: ^5.6.2
  firebase_core: ^3.15.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  freezed_annotation: ^3.0.0
  intl: ^0.20.0
  json_annotation: ^4.9.0
  permission_handler: ^12.0.1
  shimmer: ^3.0.0
  wo_form: ^1.2.1
  yaml: ^3.1.3

dependency_overrides:
  wo_form:
    git: https://github.com/Womotaq/wo_form.git
    # path: ../wo_form

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
