name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    uses: Womotaq/github_actions/.github/workflows/flutter_checks.yaml@main
    with:
      pre_build_command: "dart lib/wo_form_version/generate_version.dart"
    secrets:
      FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
