name: Build and Deploy to wo-form.womotaq.com

on:
  pull_request:
    branches:
      - main
  push: # TODO : disallow push to main
    branches:
      - main

# https://medium.com/@colonal/automating-flutter-builds-and-releases-with-github-actions-77ccf4a1ccdd
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # runs-on: macos-latest # ensures an ios build possibility

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # For android builds
      # Duration: ~3 minutes
      # - name: Set Up Java
      #   uses: actions/setup-java@v3.12.0
      #   with:
      #     distribution: "oracle"
      #     java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Create dotenv file
        run: echo "${{ secrets.DOTENV_FILE }}" > assets/assets/dotenv

      - name: Update wo_form version file
        run: dart lib/wo_form_version/generate_version.dart

      - name: Build Flutter Web
        run: flutter build web

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: "${{ env.FIREBASE_PROJECT_ID }}"
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Check if Tag Exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Modify Tag
        if: env.TAG_EXISTS == 'true'
        id: modify_tag
        run: |
          new_version="${{ env.VERSION }}-build-${{ github.run_number }}"
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Create Git tag
        id: create_tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${VERSION}" -m "Release v${VERSION}"
          git push origin "v${VERSION}"
