name: Deploy

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    uses: Womotaq/github_actions/.github/workflows/flutter_deploy_web.yaml@main
    secrets:
      FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
