name: Deploy

on:
  push:
    branches: [main]

jobs:
  call-flutter_deploy_web:
    uses: Womotaq/github_actions/.github/workflows/flutter_deploy_web.yaml@v1.0.0
    with:
      pre_build_command: "dart lib/wo_form_version/generate_version.dart"
    secrets: inherit
