name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy_using_flutter_deploy_web:
    uses: Womotaq/github_actions/.github/workflows/flutter_deploy_web.yaml@main
    secrets:
      FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
